#!/usr/bin/env sh

bspc monitor -d I II III IV

bspc config border_width            0
bspc config window_gap              0
bspc config split_ratio             0.5

# Use super + mouse to resize (left-click) and swap (right-click) nodes
bspc config pointer_modifier        mod4
bspc config pointer_action1         resize_corner
bspc config pointer_action3         move

# Monocle mode imitates fullscreen, but does not try to expand behind bar
bspc config borderless_monocle      true
bspc config gapless_monocle         true
bspc config paddingless_monocle     false

# Focus under pointer, but do not alter cursor position
bspc config focus_follows_pointer   true
bspc config pointer_follows_focus   false

# Load and apply colors before relaunching other graphical processes
xrdb -merge -quiet "${HOME}/.Xresources"
. "${HOME}/bin/custom/sourceme/xcolors"

pkill dunst
dunst \
    -lb "$bg"      \
    -nb "$bg"      \
    -cb "#ff0000"  \
    -lf "$fg"      \
    -bf "$fg"      \
    -cf "#000000"  \
    -nf "$fg" &

pkill -f tatami-bar
pkill lemonbar
"${HOME}/bin/tatami-bar" | lemonbar -B "$bg" -F "$fg" -U "$fg" -g x24 -u 3 \
    -f '-lucy-tewi-medium-*-*-*-11-*-*-*-*-*-*-*' &

pkill stalonetray
stalonetray -c "${XDG_CONFIG_HOME}/stalonetray/stalonetrayrc" -bg "$bg"
