#!/usr/bin/env sh

bspc monitor -d I II III IV

bspc config border_width            0
bspc config window_gap              24

bspc config split_ratio             0.50
bspc config top_padding             40
bspc config bottom_padding          20
bspc config left_padding            20
bspc config right_padding           20

# Use super + mouse to resize (left-click) and swap (right-click) nodes
bspc config pointer_modifier        mod4
bspc config pointer_action1         resize_corner
bspc config pointer_action3         move

# Monocle mode imitates fullscreen
bspc config borderless_monocle      true
bspc config gapless_monocle         true
bspc config paddingless_monocle     true

# Focus under pointer, but do not alter cursor position
bspc config focus_follows_pointer   true
bspc config pointer_follows_focus   false

# Monitor stuff
bspc config remove_disabled_monitors  true
bspc config remove_unplugged_monitors true


# Load and apply fonts + colors
xset +fp "${HOME}/.local/share/fonts/tewi"
xrdb -merge -quiet "${HOME}/.Xresources"
. "${HOME}/bin/custom/source-xcolors

pkill dunst
dunst \
    -lb "$bg"      \
    -nb "$bg"      \
    -cb "#ff0000"  \
    -lf "$fg"      \
    -bf "$fg"      \
    -cf "#000000"  \
    -nf "$fg" &

pkill tatami-bar
pkill lemonbar
"${HOME}/bin/tatami-bar" | lemonbar -B "$bg" -F "$fg" -g x24 -u 2 \
    -f '-lucy-tewi-medium-r-*-*-11-*-*-*-*-*-*-*' &
