#!/bin/sh

bspc monitor -d I II III IV V

# super + mouse to resize (left-click) and swap (right-click) nodes
bspc config pointer_modifier        mod4
bspc config pointer_action1         resize_corner
bspc config pointer_action3         move

# monocle mode imitates fullscreen but respects top/bottom padding
bspc config borderless_monocle      true
bspc config gapless_monocle         true
bspc config paddingless_monocle     true

# focus under pointer, but do not alter cursor position
bspc config focus_follows_pointer   true
bspc config pointer_follows_focus   false

# init/reload graphical programs
xrdb -merge "${XDG_CONFIG_HOME}/dotfiles/colors/colors.Xresources"
xrdb -merge "${XDG_CONFIG_HOME}/Xresources.d/all"

. "${XDG_CONFIG_HOME}/dotfiles/colors"

bspc config normal_border_color "$color0"
bspc config focused_border_color "$color15"

pkill dunst; dunst \
    -lb "$color0"  \
    -nb "$color0"  \
    -cb "#ff0000"  \
    -lf "$color15" \
    -bf "$color15" \
    -cf "#000000"  \
    -nf "$color15" &

pkill polybar; polybar bar &
