#!/bin/bash

while read file
do
    case "$1" in
    "C-d")
        trash-put "$file" && \
        notify-send "[sxiv] trashed ${file}" ;;
    "C-c")
        xclip -selection clipboard \
            -t "$(file --mime-type -b "$file")" -i "$file" && \
        notify-send "[sxiv] copied "$(basename "$file")" to clipboard" ;;
    esac
done
